### ISSUE TITLE
Add demo videos

### ISSUE THREAD

**Issue by eugeniaguerrero** [exchai93/alexa_sous_chef#21]

**Comment by exchai93-zz** [comment]
Our problem: 
- phone dimming 
- shot of mess on laptop / phone / ipad

**Comment by exchai93-zz** [comment]
Alexa in action:
- 'open sous chef' 
- 'search recipes with .....'
-  'pick 1'
- read ingredients (altogether)
- step by step preparation steps (first and last)
- finished product

**Comment by exchai93-zz** [comment]
- last shot of a Happy chef
